language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate

virtualenv:
  system_site_packages: true

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
