language: python

python:
    - "3.8"
env:
    - SECRET_KEY='232wedfvb7ibt8p6ptrvw54p98097b0n888rfi7fligcqy5scduuyib9p8br52wci869o7ju'

install:
    - pip3 install -r requirements.txt

script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always